# Generated by Django 5.0 on 2023-12-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='telephone',
            new_name='Celular',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='Mensaje',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Nombre',
        ),
    ]
